### ISSUE TITLE
Background image in all the html pages

### ISSUE THREAD

**Issue by mbj36** [Book-Store/book-store.github.io#20]
As in landing page, we see a background image, i want same background image to be in all the html pages (presently they are grey) .

**Comment by mbj36** [comment]
@raj-maurya  Could you look up to this issue ?

**Comment by raj-maurya** [comment]
Sure! @mbj36

**Comment by mbj36** [comment]
@raj-maurya make sure you make single commit, multiple commits won't be acceptable :)

**Comment by tanayag** [comment]
Please Review #21

**Comment by mbj36** [comment]
@tanayag you should assign/comment before working on any issue so that two people don't work on same issue :)

**Comment by tanayag** [comment]
@mbj36 sorry, I will remember from next time.

Merge mine only if @raj-maurya didn't started working on this issue, otherwise it is fine.

**Comment by mbj36** [comment]
Thanks @tanayag
