### ISSUE TITLE
In small view you got problem

### ISSUE THREAD

**Issue by sunil-sopho** [Book-Store/book-store.github.io#32]
For mobile version of site when a the button of drop down menu is pressed and clicked somewhere on page drop down not returning to its original state it is waiting to be pressed again or page reload to contract again.

**Comment by Shruti9520** [comment]
Hi @sunil-sopho 
Thanks for finding an issue. :)
Do you want to submit a Pull Request?

Thanks!

**Comment by sunil-sopho** [comment]
I Would be happy to but I am very busy for 5 days maybe after that I will.Sorry for a late reply

**Comment by Shruti9520** [comment]
@sunil-sopho That's great. Thank you! :)

**Comment by sunil-sopho** [comment]
Pull request made with problem corrected.
